# Generated by Django 5.2.8 on 2025-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(max_length=20, unique=True, verbose_name='사업자등록번호')),
                ('company_name', models.CharField(max_length=100, verbose_name='상호명')),
                ('ceo_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='대표자명')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초수집일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근갱신일')),
            ],
        ),
    ]
