# Generated by Django 5.2.8 on 2025-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
